### ISSUE TITLE
Unable to access console button during upscaling

### ISSUE THREAD

**Issue by zesky18** [the-database/MangaJaNaiConverterGui#20]
When I went to batch upscale my manga, I forgot to open the console. I try to open it but the button was pushed off-screen making it impossible to do so.

![2024_07_07_01-07__a9O](https://github.com/the-database/MangaJaNaiConverterGui/assets/24356774/d5b059a6-ff1e-4416-8fc8-ecfd662ff8e4)

**Comment by the-database** [comment]
Fixed in v1.1.5
