### ISSUE TITLE
Cannot upscale after new update

### ISSUE THREAD

**Issue by TrafalgarSP** [the-database/MangaJaNaiConverterGui#55]
![Screenshot 2024-12-01 131348](https://github.com/user-attachments/assets/6f734ee3-4d7b-448c-8624-56cd3c6a052f)
I don't now a lot about pythons so how do i fix this error? I already try reinstall it, still not work.

**Comment by the-database** [comment]
Hi, some other users have been reporting the same issue on the new version. Could you please navigate to `%appdata%\mangajanaiconvertergui\logs` in your file explorer, and then share the `install.log` folder here?

**Comment by sbsdlat** [comment]
After being updated to version 1.2.1, the software will report this error. Then I tried to reinstall it back to version 1.1.8, but it still reported this error. Using the "Reinstall Python Environment" function of the software couldn't solve this problem either.

**Comment by the-database** [comment]
> After being updated to version 1.2.1, the software will report this error. Then I tried to reinstall it back to version 1.1.8, but it still reported this error. Using the "Reinstall Python Environment" function of the software couldn't solve this problem either.

Try uninstalling MangaJaNaiCoverterGui first, then install 1.1.8. Does that resolve the error?

**Comment by sbsdlat** [comment]
> > After being updated to version 1.2.1, the software will report this error. Then I tried to reinstall it back to version 1.1.8, but it still reported this error. Using the "Reinstall Python Environment" function of the software couldn't solve this problem either.
> 
> Try uninstalling MangaJaNaiCoverterGui first, then install 1.1.8. Does that resolve the error?

I tried uninstalling it and then reinstalling it. I repeated this process many times, include uninstalling and then use portable version. But it still reported this error.

**Comment by the-database** [comment]
> > > After being updated to version 1.2.1, the software will report this error. Then I tried to reinstall it back to version 1.1.8, but it still reported this error. Using the "Reinstall Python Environment" function of the software couldn't solve this problem either.
> > 
> > 
> > Try uninstalling MangaJaNaiCoverterGui first, then install 1.1.8. Does that resolve the error?
> 
> I tried uninstalling it and then reinstalling it. I repeated this process many times, include uninstalling and then use portable version. But it still reported this error.

Do you have an install.log file in the %appdata%\mangajanaiconvertergui\logs folder  you're able to share?

**Comment by TrafalgarSP** [comment]
> Hi, some other users have been reporting the same issue on the new version. Could you please navigate to `%appdata%\mangajanaiconvertergui\logs` in your file explorer, and then share the `install.log` file here?[install.log](https://github.com/user-attachments/files/17973773/install.log)

**Comment by the-database** [comment]
> > Hi, some other users have been reporting the same issue on the new version. Could you please navigate to `%appdata%\mangajanaiconvertergui\logs` in your file explorer, and then share the `install.log` file here?[install.log](https://github.com/user-attachments/files/17973773/install.log)

Thanks. This log file shows that Windows Defender is blocking part of the Python dependency installation, which causes the upscales to fail. Specifically, the [pyvips](https://github.com/libvips/pyvips) package is being blocked, which was introduced in the latest version of MangaJaNai, which is why this wasn't happening in older versions. One workaround is to temporarily disable antivirus while installing the Python dependencies, but this is at your own risk. 

I'm unable to reproduce this issue on my own PCs which makes this difficult to resolve but I'll keep working on it and see if there's a better way to resolve the issue for everyone without disabling anti virus.

**Comment by sbsdlat** [comment]
> > > > After being updated to version 1.2.1, the software will report this error. Then I tried to reinstall it back to version 1.1.8, but it still reported this error. Using the "Reinstall Python Environment" function of the software couldn't solve this problem either.
> > > 
> > > 
> > > Try uninstalling MangaJaNaiCoverterGui first, then install 1.1.8. Does that resolve the error?
> > 
> > 
> > I tried uninstalling it and then reinstalling it. I repeated this process many times, include uninstalling and then use portable version. But it still reported this error.
> 
> Do you have an install.log file in the %appdata%\mangajanaiconvertergui\logs folder you're able to share?

There is no install.log file in the %appdata%\mangajanaiconvertergui\logs folder. But I know how to fix this problem now. After reinstalling the software, many necessary modules are missing in the folder "\AppData\Roaming\MangaJaNaiConverterGui\python\python\Lib\site-packages". Only after manually installing these modules can the software perform the upscale function normally. It should be noted that when manually installing these modules, they will be installed into the "libs" folder under the default path of Python. You need to copy the corresponding modules from there to the "\AppData\Roaming\MangaJaNaiConverterGui\python\python\Lib\site-packages" folder. Once all the modules are supplemented, the software can work properly.

**Comment by the-database** [comment]
I made some test updates in https://github.com/the-database/MangaJaNaiConverterGui/releases/tag/1.2.2, please let me know if this works any better than 1.2.1.

**Comment by TrafalgarSP** [comment]
> Owner

sorry for the late reply, it seems like it work perfectly fine like before. Thank you for update.
