### ISSUE TITLE
Some color images are detected as grayscale

### ISSUE THREAD

**Issue by the-database** [the-database/MangaJaNaiConverterGui#7]

**Comment by jonathanluepfert** [comment]
Adjusting the threshold in line 230 of runmangajaiconverterguiupscale.py from 5 to 0.2 seems to have fixed this in my case.

**Comment by Geniusssmit** [comment]
it's always turns greyscale with these models

**Comment by Geniusssmit** [comment]
stays colored with 4x_MangaJaNai_V0.5_100k.pth model
and disabled Preprocessing -> Auto Adjust Levels on Grayscale Images

**Comment by the-database** [comment]
> ![Dl-Raw Net-03](https://private-user-images.githubusercontent.com/24941285/324881950-a78d94ac-7ef7-4f62-aa55-86705a84cb65.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NzA1NzAsIm5iZiI6MTcxMzk3MDI3MCwicGF0aCI6Ii8yNDk0MTI4NS8zMjQ4ODE5NTAtYTc4ZDk0YWMtN2VmNy00ZjYyLWFhNTUtODY3MDVhODRjYjY1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDE0NTExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViZmZjZTAyNjQxMjE4ZWMwOWViZGVhYzc3NGY4ZDVmZDE0OGEzMjg2NzkzNmYzZTQyN2M2N2MwNDMzODJjM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zm1t8m3OSeLYWi3O2mmJTG_QVox96q5AcGUT00ad3AA) not able to upscale this page colored. Please help models used .\chaiNNer\models\4x_MangaJaNai_Grayscale_1200_V1_ESRGAN_70k.pth .\chaiNNer\models\4x_IllustrationJaNai_V1_ESRGAN_135k.pth

Thanks for sharing this test image, it is still incorrectly being detected as grayscale, will investigate.
