### ISSUE TITLE
Possibly to do 2x or 3x instead of 4x?

### ISSUE THREAD

**Issue by EliCodesForFun** [the-database/MangaJaNaiConverterGui#8]
Hi,
What can I change in the code to make this output at a different scale, if possible? Been digging through and trying to find a way to do 2x or 3x. 4x is kind of overkill for my use.

**Comment by the-database** [comment]
Currently there is only a 4x model, but in the GUI if you choose Show More Settings and go to the bottom under Postprocessing, you can set the resize after upscaling. To do a 2x upscale you could set the Resize Factor After Upscale to 50% and to do 3x you could set that setting to 75%.

**Comment by EliCodesForFun** [comment]
> Currently there is only a 4x model, but in the GUI if you choose Show More Settings and go to the bottom under Postprocessing, you can set the resize after upscaling. To do a 2x upscale you could set the Resize Factor After Upscale to 50% and to do 3x you could set that setting to 75%.

Got it, this works perfectly 😎 
Would be cool to have in the future as 2x would probably be a bit faster for bulk conversion, but this has been a great tool so far! Speaking of which, that direct zip conversion is crazy convenient.

**Comment by the-database** [comment]
> > Currently there is only a 4x model, but in the GUI if you choose Show More Settings and go to the bottom under Postprocessing, you can set the resize after upscaling. To do a 2x upscale you could set the Resize Factor After Upscale to 50% and to do 3x you could set that setting to 75%.
> 
> Got it, this works perfectly 😎 Would be cool to have in the future as 2x would probably be a bit faster for bulk conversion, but this has been a great tool so far! Speaking of which, that direct zip conversion is crazy convenient.

Out of curiosity I did some benchmarks for upscaling 35 959x1400 images with 4x ESRGAN vs 2x ESRGAN (just some random 2x ESRGAN model since I haven't trained one for manga yet). 

4x ESRGAN 1st run: 70 seconds
4x ESRGAN 2nd run: 72 seconds
2x ESRGAN 1st run: 19 seconds
2x ESRGAN 2nd run: 20 seconds

Looks like 2x models will be worth training for sure.

**Comment by the-database** [comment]
Added in 1.0.0
